### ISSUE TITLE
'RIGHT SINGLE QUOTATION MARK' (U+2019) in jokes causes traceback on Python 3 in Windows

### ISSUE THREAD

**Issue by gmarkall** [pyjokes/pyjokes#26]
These two jokes in the neutral category:

'Knock, knock.' 'Who’s there?' ... very long pause ... 'Java.'
3 Database Admins walked into a NoSQL bar. A little while later they walked out because they couldn’t find a table.

contain a U+2019 character for the apostrophe in "Who's" and "couldn't" - when they are printed, the following traceback is produced on Windows:

```
[py34np19] C:\Program Files\Microsoft SDKs\Windows\v7.0>pyjoke
Traceback (most recent call last):
  File "C:\Users\gmarkall\Miniconda3\envs\py34np19\Scripts\pyjoke-script.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyjokes==0.5.0', 'pyjoke')
  File "C:\Users\gmarkall\Miniconda3\envs\py34np19\lib\site-packages\setuptools-18.1-py3.4.egg\pkg_resources\__init__.py", line 735, in run_script
  File "C:\Users\gmarkall\Miniconda3\envs\py34np19\lib\site-packages\setuptools-18.1-py3.4.egg\pkg_resources\__init__.py", line 1659, in run_script
  File "C:\Users\gmarkall\Miniconda3\envs\py34np19\lib\site-packages\pyjokes-0.5.0-py3.4.egg\EGG-INFO\scripts\pyjoke", line 54, in <module>
  File "C:\Users\gmarkall\Miniconda3\envs\py34np19\lib\site-packages\pyjokes-0.5.0-py3.4.egg\EGG-INFO\scripts\pyjoke", line 51, in main
  File "C:\Users\gmarkall\Miniconda3\envs\py34np19\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2019' in position 20: character maps to <undefined>
```

I guess this is because Windows is using a different character encoding to other OSes - I've seen the Java joke get printed out successfully on my Linux machine so it seems not to be a problem there.

**Comment by oiertwo** [comment]
I think for now ask people to write with " ' " should be enough. But we should find some long term solution. Thanks @gmarkall !

**Comment by gmarkall** [comment]
Thanks for merging!

> I think for now ask people to write with " ' " should be enough. But we should find some long term solution. 

Yes, this is the "easy" fix for now :-) ... I don't know too much about character mappings and encodings so I wasn't sure what the long-term solution ought to be.

**Comment by bennuttall** [comment]
I wonder if we can add a check for rougue characters to our test suite...

**Comment by oiertwo** [comment]
Already done :P
